### ISSUE TITLE
hex sticker design issue

### ISSUE THREAD

**Issue by YoungjunNa** [statgarten/scissor#1]
scissor의 hex sticker 디자인을 해보려고 하는데요.
패키지에 대한 간단한 소개 + 이름을 지은 목적에 대해서 reply 해주시면 참고해 보도록 하겠습니다.

**Comment by jhk0530** [comment]
데이터 분석 작업에 필요한 wrangling 을 `shiny`에 지원하는 목적으로 만든 패키지입니다. 
데이터를 잘라낸다는 의미로 `scissor`라고 지었어요.

**Comment by YoungjunNa** [comment]
고맙습니다! 참고해서 잘 만들어 볼게요 :)
